SELECT * FROM SIGER.URUGUAY_RESTRICCIONES
WHERE ((APELLIDO = :APELLIDO AND NOMBRE = :NOMBRE AND FECHA_NAC = TO_DATE(:FECHA, 'dd/mm/yyyy'))
OR
(APELLIDO = :APELLIDO AND NOMBRE = :NOMBRE AND NUM_DOC = :DOCUMENTO)
OR  (NUM_DOC = :DOCUMENTO AND PAIS_DOC = :EMISOR_DOC)
)